// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjc39yX4Ou7tN8ECowGKZ5lFRSOp3Lm70',
    appId: '1:13742574925:web:ce74966c3fc7894442fb04',
    messagingSenderId: '13742574925',
    projectId: 'roombooking-f4b89',
    authDomain: 'roombooking-f4b89.firebaseapp.com',
    storageBucket: 'roombooking-f4b89.appspot.com',
    measurementId: 'G-PDERLDQE12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDur3gCIE03E8ROIti4DyJImjf8Czb8iXQ',
    appId: '1:13742574925:android:97b91176cbc13bef42fb04',
    messagingSenderId: '13742574925',
    projectId: 'roombooking-f4b89',
    storageBucket: 'roombooking-f4b89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXxgYWdfexOCrKBf3mUaLyQcdQl5XMBWo',
    appId: '1:13742574925:ios:cf2e1d9d547cf70542fb04',
    messagingSenderId: '13742574925',
    projectId: 'roombooking-f4b89',
    storageBucket: 'roombooking-f4b89.appspot.com',
    iosBundleId: 'com.example.roombooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXxgYWdfexOCrKBf3mUaLyQcdQl5XMBWo',
    appId: '1:13742574925:ios:b75b36ce0ce8016042fb04',
    messagingSenderId: '13742574925',
    projectId: 'roombooking-f4b89',
    storageBucket: 'roombooking-f4b89.appspot.com',
    iosBundleId: 'com.example.roombooking.RunnerTests',
  );
}
